version: '3.9'
services:

  suricata:
    build:
        context: .
        dockerfile: centos8-suricata.Dockerfile
        args:
          suricata_version: 5.0
    image: local/centos8.3.2011-suricata
    restart: unless-stopped
    container_name: suricata
    volumes:
      - suricata_configs:/etc/suricata
      - suricata_rulesets:/var/lib/suricata
      - suricata_logs:/var/log/suricata
    stdin_open: true
    tty: true

  gitlab:
    image: 'gitlab/gitlab-ee:13.6.3-ee.0'
    restart: unless-stopped
    hostname: 'awx-gitlab'
    container_name: gitlab
    environment:
      TZ: America/Chicago
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://awx-gitlab:8330'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8330:8330'
      - '2224:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  gitlab-runner:
    image: 'gitlab/gitlab-runner:ubuntu-v13.6.0'
    restart: unless-stopped
    hostname: 'awx-gitlab-runner'
    container_name: gitlab-runner
    environment:
      TZ: America/Chicago
    volumes:
      - gitlab-runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      
  web:
    build:
        context: .
        dockerfile: awx.Dockerfile
        args:
          ansible_version: 2.10.4
    image: local/ansible2.10.4_awx16.0.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - suricata_configs:/etc/suricata
      - suricata_rulesets:/var/lib/suricata
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/etc/corelight-env/.awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/etc/corelight-env/.awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/etc/corelight-env/.awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/etc/corelight-env/.awx/awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/etc/corelight-env/.awx/awxcompose/redis_socket:/var/run/redis/:rw"
      - "/etc/corelight-env/awx/projects:/var/lib/awx/projects:rw"
      - "/etc/corelight-env/:/etc/corelight-env/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: local/ansible2.10.4_awx16.0.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - suricata_configs:/etc/suricata
      - suricata_rulesets:/var/lib/suricata
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/etc/corelight-env/.awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/etc/corelight-env/.awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/etc/corelight-env/.awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/etc/corelight-env/.awx/awxcompose/redis_socket:/var/run/redis/:rw"
      - "/etc/corelight-env/awx/projects:/var/lib/awx/projects:rw"
      - "/etc/corelight-env/:/etc/corelight-env/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "/etc/corelight-env/.awx/awxcompose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/etc/corelight-env/.awx/awxcompose/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - postgres-10-data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy: 
      https_proxy: 
      no_proxy: 


volumes:
  postgres-10-data:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
  suricata_configs:
  suricata_rulesets:
  suricata_logs:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab-runner_config:
